---
build:
  preview_env:
  - NODE_ENV=staging
  preview_output_directory: dist/browser
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run watch
