---
build:
  preview_env:
  - TARGET_ENV=staging
  preview_output_directory: dist/
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run watch
